### ISSUE TITLE
PERSISTED QUERY NOT FOUND

### ISSUE THREAD

**Issue by Ikosse** [Ikosse/plugin.video.teliaplay-se#8]
Please report here if you encounter the error message: PERSISTED QUERY NOT FOUND, and I will update the hashes as soon as possible.

**Comment by OriginalTempest** [comment]
Hi,

Today 28th nov 2022 i got error "PERSISTED QUERY NOT FOUND".
Would be quite happy if you fix it.

Many Thanks
OriginalTempest

**Comment by Ikosse** [comment]
Thank you for reporting. It should be fixed now!

**Comment by OriginalTempest** [comment]
Working Perfect

Thank You
OriginalTempest

**Comment by Ikosse** [comment]
It happens every now and then, but I will fix asap!

**Comment by tux2000** [comment]
Many hashes are already updated in #11 and the search endpoint had changed, so I fixed that in there as well... That version worked for my use case.

**Comment by Ikosse** [comment]
Sorry I missed your PR, but it looks good to me so I merged it. Thank you :)

**Comment by aiobofh** [comment]
This seems to be an issue, still

**Comment by luxwarp** [comment]
Got the error today! :)

**Comment by tomoqv** [comment]
Fresh install on Kodi 21.0 Omega, same error. I have installed the addon, uninstalled, restarted, installed again and problem persists. Found this in the log searching for teliaplay:

```
2024-06-17 21:01:53.883 T:1108     info <general>: CAddonMgr::FindAddon: plugin.video.teliaplay-se v1.2.7+matrix.1 installed
2024-06-17 21:01:54.114 T:1097  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-06-17 21:01:55.773 T:1140    error <general>: AddOnLog: pvr.hts: unable to connect to 192.168.1.122:9982
```

Don't know if it has anything to do with it.

**Comment by tomoqv** [comment]
The issue is still present. I did a clean install of the latest LibreElec (Omega) today. After adding my credential in the config, I get the "PERSISTED QUERY NOT FOUND" every time I open the addon. Considering a LibreElec downgrade until this is working.

**Comment by aiobofh** [comment]
I get this as well.... (21 Omega) I have no clue on how to get this working. What is it actually trying to do? Do one HAVE to enter the PIN1 thing?

Regardless i get "PERSISTED QUERY NOT FOUND"

**Comment by tomoqv** [comment]
I ended up downgrading to Kodi v 20 Nexus and now the addon works again.

**Comment by aiobofh** [comment]
I was hoping not to downgrade... Let's hop @Ikosse finds it in his heart and find the time to fix the 21 version of the addon as is.
